"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import FeedbackToast from "@/components/common/FeedbackToast";

type Inventory = { id: string; quantity: number; item: { name: string }; storageLocation: { name: string } | null };
type Listing = { id: string; title: string; channel: string; externalListingId: string | null; price: number; listedQuantity: number; soldQuantity: number; status: string; updatedAt: string; inventoryInstance: Inventory };
const statusLabel: Record<string,string> = { DRAFT: "出品準備中", READY: "出品可能", LISTED: "出品中", SOLD: "売却済み", CANCELLED: "取消" };

export default function MarketplacePage() {
  const [listings, setListings] = useState<Listing[]>([]); const [inventories, setInventories] = useState<Inventory[]>([]);
  const [inventoryId, setInventoryId] = useState(""); const [price, setPrice] = useState(""); const [quantity, setQuantity] = useState("1"); const [channel, setChannel] = useState("flea_market");
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [working, setWorking] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/admin/marketplace/listings", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "フリマ情報を取得できませんでした。"); setListings(data.listings); setInventories(data.inventories); }, []);
  useEffect(() => { void load().catch((e) => setError(e instanceof Error ? e.message : "取得できませんでした。")); }, [load]);
  const selected = useMemo(() => inventories.find((entry) => entry.id === inventoryId), [inventories, inventoryId]);
  const create = async () => { setWorking("create"); setError(""); try { const response = await fetch("/api/admin/marketplace/listings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ inventoryInstanceId: inventoryId, title: selected?.item.name, price: Number(price), listedQuantity: Number(quantity), channel }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setNotice(data.message); setPrice(""); await load(); } catch (e) { setError(e instanceof Error ? e.message : "追加できませんでした。"); } finally { setWorking(""); } };
  const update = async (id: string, status: string) => { setWorking(id); setError(""); try { const response = await fetch("/api/admin/marketplace/listings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setNotice(data.message); await load(); } catch (e) { setError(e instanceof Error ? e.message : "更新できませんでした。"); } finally { setWorking(""); } };
  return <main className="min-h-screen bg-slate-100 p-4 text-slate-950 sm:p-8"><FeedbackToast tone="error" title="フリマ連携エラー" message={error} onClose={() => setError("")} /><FeedbackToast tone="success" title="反映完了" message={notice} onClose={() => setNotice("")} /><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-black text-pink-700">SALES CHANNEL</p><h1 className="mt-1 text-3xl font-black">フリマ出品・販売連携</h1><p className="mt-2 text-slate-700">出品から売却までを在庫と一元管理します。</p></div><div className="flex gap-2"><a href="/api/admin/marketplace/listings?format=csv" className="rounded-xl bg-emerald-600 px-4 py-3 font-black text-white">CSV出力</a><Link href="/admin" className="rounded-xl bg-slate-800 px-4 py-3 font-black text-white">管理者メニュー</Link></div></header>
  <section className="mt-7 rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">出品候補へ追加</h2><div className="mt-4 grid gap-3 md:grid-cols-4"><select value={inventoryId} onChange={(e) => setInventoryId(e.target.value)} className="rounded-xl border p-3 font-bold"><option value="">商品を選択</option>{inventories.map((entry) => <option key={entry.id} value={entry.id}>{entry.item.name}／在庫{entry.quantity}／{entry.storageLocation?.name || "場所未設定"}</option>)}</select><select value={channel} onChange={(e) => setChannel(e.target.value)} className="rounded-xl border p-3"><option value="flea_market">フリマ共通</option><option value="mercari">メルカリ</option><option value="rakuma">ラクマ</option><option value="yahoo_furima">Yahoo!フリマ</option></select><input type="number" min="1" value={price} onChange={(e) => setPrice(e.target.value)} placeholder="販売価格" className="rounded-xl border p-3" /><input type="number" min="1" max={selected?.quantity} value={quantity} onChange={(e) => setQuantity(e.target.value)} placeholder="出品数" className="rounded-xl border p-3" /></div><button type="button" disabled={!inventoryId || !price || working === "create"} onClick={() => void create()} className="mt-4 rounded-xl bg-pink-600 px-5 py-3 font-black text-white disabled:bg-slate-300">出品候補へ追加</button></section>
  <section className="mt-6 space-y-3">{listings.length === 0 ? <div className="rounded-2xl bg-white p-8 text-center font-bold text-slate-500">出品データはありません。</div> : listings.map((entry) => <article key={entry.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="rounded-full bg-pink-100 px-3 py-1 text-xs font-black text-pink-800">{statusLabel[entry.status] || "確認中"}</span><h2 className="mt-3 text-xl font-black">{entry.title}</h2><p className="mt-1 text-sm font-semibold text-slate-600">{entry.channel}・在庫 {entry.inventoryInstance.quantity}・出品 {entry.listedQuantity}</p><p className="mt-2 text-2xl font-black">¥{entry.price.toLocaleString("ja-JP")}</p></div>{!["SOLD","CANCELLED"].includes(entry.status) && <div className="flex flex-wrap gap-2">{entry.status === "DRAFT" && <button onClick={() => void update(entry.id,"READY")} disabled={working === entry.id} className="rounded-xl bg-blue-600 px-4 py-2 font-black text-white">準備完了</button>}{["DRAFT","READY"].includes(entry.status) && <button onClick={() => void update(entry.id,"LISTED")} disabled={working === entry.id} className="rounded-xl bg-violet-600 px-4 py-2 font-black text-white">出品開始</button>}<button onClick={() => void update(entry.id,"SOLD")} disabled={working === entry.id} className="rounded-xl bg-emerald-600 px-4 py-2 font-black text-white">売却・在庫反映</button><button onClick={() => void update(entry.id,"CANCELLED")} disabled={working === entry.id} className="rounded-xl bg-slate-600 px-4 py-2 font-black text-white">取消</button></div>}</div></article>)}</section></div></main>;
}
