import {beforeEach,expect,it,vi} from "vitest";
const db=vi.hoisted(()=>({$queryRaw:vi.fn(),stocktakeSession:{findMany:vi.fn()},stocktakeRecord:{findMany:vi.fn()},inventoryInstance:{findMany:vi.fn()}}));vi.mock("@/lib/prisma",()=>({prisma:db}));
import {inspectionTargets} from "../src/lib/inspection-targets";
const date=new Date("2026-09-10T00:00:00Z");
beforeEach(()=>{vi.resetAllMocks();db.$queryRaw.mockResolvedValue([{id:"i"}]);db.inventoryInstance.findMany.mockResolvedValue([{id:"i",itemId:"p",unit:"0",lotNo:"LOT-A",storageLocation:{name:"倉庫"},updatedAt:date,majorCategory:"旧分類",minorCategory:null,manufacturer:null,item:{name:"商品A",defaultUnit:"個",updatedAt:date,majorCategory:"新分類",minorCategory:null,manufacturer:null}}]);db.stocktakeRecord.findMany.mockResolvedValue([]);});
it("shows the exact lot, location, invalid value, expected meaning and destination",async()=>{const data=await inspectionTargets("CHECK_INVALID_UNITS",null,null);expect(data.targets[0]).toMatchObject({name:"商品A",lot:"LOT-A",location:"倉庫",current:"在庫単位：0 / 商品の標準単位：個",action:"SET_UNIT",href:"/items/p?inventoryId=i#inventory-i"});});
it("previews the actual metadata differences instead of a generic instruction",async()=>{expect((await inspectionTargets("CHECK_PRODUCT_LINKS",null,null)).targets[0]).toMatchObject({differences:[{field:"大分類",before:"旧分類",after:"新分類"}]});});
it("matches a record to a target in the same session and binds external values",async()=>{await inspectionTargets("CHECK_STOCKTAKE_TARGET_LINK","worker-session","' OR TRUE --");const query=db.$queryRaw.mock.calls[0][0];expect(query.sql).toContain('t."sessionId"=r."sessionId"');expect(query.sql).toContain('t."inventoryInstanceId"=r."inventoryInstanceId"');expect(query.sql).not.toContain("' OR TRUE");expect(query.values).toContain("worker-session");expect(query.values).toContain("' OR TRUE --");});
it("does not list other workers' active sessions as a repair target",async()=>{db.stocktakeSession.findMany.mockResolvedValue([{id:"s",title:"田中さんの棚卸",operatorUser:{displayName:"田中"},status:"CONFLICT",updatedAt:date,_count:{targets:8,records:3}}]);const data=await inspectionTargets("CHECK_STOCKTAKE_LEGACY_STATE",null,null);expect(db.stocktakeSession.findMany.mock.calls[0][0].where).toEqual({status:"CONFLICT"});expect(data.targets[0]).toMatchObject({owner:"田中",current:"保存済み入力 3件 / 対象 8件"});});
