import { beforeEach, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";
const state=vi.hoisted(()=>({allowed:true}));const db=vi.hoisted(()=>({$transaction:vi.fn(),systemCheckRun:{findUnique:vi.fn()},errorReport:{updateMany:vi.fn()},adminActionLog:{create:vi.fn()}}));
vi.mock("@/lib/auth",()=>({requireAdmin:()=>({user:{id:"admin"},response:state.allowed?null:new Response(null,{status:403})}),getAdminElevation:()=>null}));vi.mock("@/lib/prisma",()=>({prisma:db}));
import { PATCH } from "../src/app/api/admin/system-check/reports/route";
const body={id:"report",route:"/marketplace",runId:"run",expectedAttempts:2,reason:"接続復旧後に操作確認",verified:true};const request=(input:object)=>new NextRequest("http://localhost/api/admin/system-check/reports",{method:"PATCH",body:JSON.stringify(input)});
beforeEach(()=>{vi.resetAllMocks();state.allowed=true;db.$transaction.mockImplementation(async fn=>fn(db));db.systemCheckRun.findUnique.mockResolvedValue({mode:"AUTO",contextRoute:"/marketplace",errorReportId:"report",createdAt:new Date(),items:[{status:"PASS"}]});db.errorReport.updateMany.mockResolvedValue({count:1});});
it("requires administrator access",async()=>{state.allowed=false;expect((await PATCH(request(body)))?.status).toBe(403);expect(db.$transaction).not.toHaveBeenCalled();});
it("does not release provisional saves without a functional check",async()=>{expect((await PATCH(request({...body,verified:false})))?.status).toBe(400);expect(db.$transaction).not.toHaveBeenCalled();});
it("requires a recent successful diagnostic",async()=>{db.systemCheckRun.findUnique.mockResolvedValue({mode:"AUTO",contextRoute:"/marketplace",errorReportId:"report",createdAt:new Date(0),items:[{status:"PASS"}]});expect((await PATCH(request(body)))?.status).toBe(409);expect(db.errorReport.updateMany).not.toHaveBeenCalled();});
it("keeps the report unresolved when checks still fail",async()=>{db.systemCheckRun.findUnique.mockResolvedValue({mode:"AUTO",contextRoute:"/marketplace",errorReportId:"report",createdAt:new Date(),items:[{status:"FAIL"}]});expect((await PATCH(request(body)))?.status).toBe(409);expect(db.errorReport.updateMany).not.toHaveBeenCalled();});
it("resolves only the confirmed page report and writes its audit together",async()=>{expect((await PATCH(request(body)))?.status).toBe(200);expect(db.errorReport.updateMany).toHaveBeenCalledWith(expect.objectContaining({where:{id:"report",route:"/marketplace",recoveryStatus:"ADMIN_REQUIRED",recoveryAttempts:2}}));expect(db.adminActionLog.create).toHaveBeenCalled();});

it("rejects an empty diagnostic result",async()=>{db.systemCheckRun.findUnique.mockResolvedValue({mode:"AUTO",contextRoute:"/marketplace",errorReportId:"report",createdAt:new Date(),items:[]});expect((await PATCH(request(body)))?.status).toBe(409);expect(db.errorReport.updateMany).not.toHaveBeenCalled();});

it("rejects a successful diagnostic belonging to a different error or page",async()=>{for(const fields of [{contextRoute:"/items",errorReportId:"report"},{contextRoute:"/marketplace",errorReportId:"different"}]){db.systemCheckRun.findUnique.mockResolvedValue({mode:"AUTO",...fields,createdAt:new Date(),items:[{status:"PASS"}]});expect((await PATCH(request(body)))?.status).toBe(409);}expect(db.errorReport.updateMany).not.toHaveBeenCalled();});
