import {afterEach,expect,it,vi} from "vitest";
import {applyAppUpdate} from "../src/lib/pwa-update";
class Worker extends EventTarget {state="installed";postMessage=vi.fn();}
function setup(){const worker=new Worker();const registration={waiting:worker,installing:null,active:null,update:vi.fn(async()=>{})};const container=Object.assign(new EventTarget(),{getRegistration:vi.fn(async()=>registration)});return {worker,registration,container:container as unknown as ServiceWorkerContainer,reload:vi.fn(),progress:vi.fn()};}
afterEach(()=>vi.useRealTimers());
it("reloads once after activation even if controllerchange also fires",async()=>{const x=setup();x.worker.postMessage.mockImplementation(()=>{x.worker.state="activated";x.worker.dispatchEvent(new Event("statechange"));x.container.dispatchEvent(new Event("controllerchange"));});await applyAppUpdate(x.container,x.reload,x.progress);expect(x.reload).toHaveBeenCalledTimes(1);expect(x.worker.postMessage).toHaveBeenCalledWith({type:"SKIP_WAITING"});});
it("rejects a stalled switch rather than leaving the button busy forever",async()=>{vi.useFakeTimers();const x=setup();const task=applyAppUpdate(x.container,x.reload,x.progress,50);const assertion=expect(task).rejects.toThrow("PWA_UPDATE_TIMEOUT");await vi.advanceTimersByTimeAsync(51);await assertion;expect(x.reload).not.toHaveBeenCalled();x.container.dispatchEvent(new Event("controllerchange"));expect(x.reload).not.toHaveBeenCalled();});
it("reloads an already activated update without waiting for a missed event",async()=>{const x=setup();x.worker.state="activated";await applyAppUpdate(x.container,x.reload,x.progress);expect(x.reload).toHaveBeenCalledOnce();});
it("waits for download/install before activating",async()=>{vi.useFakeTimers();const x=setup();Object.assign(x.registration,{waiting:null,installing:x.worker});x.worker.state="installing";x.worker.postMessage.mockImplementation(()=>{x.worker.state="activated";x.worker.dispatchEvent(new Event("statechange"));});const task=applyAppUpdate(x.container,x.reload,x.progress,100);await vi.advanceTimersByTimeAsync(1);expect(x.reload).not.toHaveBeenCalled();x.worker.state="installed";Object.assign(x.registration,{waiting:x.worker});x.worker.dispatchEvent(new Event("statechange"));await task;expect(x.registration.update).toHaveBeenCalledOnce();expect(x.reload).toHaveBeenCalledOnce();});
it("surfaces installation failure",async()=>{const x=setup();Object.assign(x.registration,{waiting:null,installing:x.worker});x.worker.state="redundant";await expect(applyAppUpdate(x.container,x.reload,x.progress)).rejects.toThrow("PWA_UPDATE_INSTALL_FAILED");expect(x.reload).not.toHaveBeenCalled();});
it("surfaces reload refusal without masking unsaved work",async()=>{const x=setup();x.worker.state="activated";x.reload.mockImplementation(()=>{throw new Error("UNSAVED");});await expect(applyAppUpdate(x.container,x.reload,x.progress)).rejects.toThrow("UNSAVED");});
it("surfaces message delivery failure",async()=>{const x=setup();x.worker.postMessage.mockImplementation(()=>{throw new Error("dead worker");});await expect(applyAppUpdate(x.container,x.reload,x.progress)).rejects.toThrow("PWA_UPDATE_SEND_FAILED");});
