ALTER TYPE "FeaturePermission" ADD VALUE IF NOT EXISTS 'STOCKTAKE_START';
ALTER TYPE "FeaturePermission" ADD VALUE IF NOT EXISTS 'MARKETPLACE';
ALTER TYPE "FeaturePermission" ADD VALUE IF NOT EXISTS 'MARKETPLACE_SETTINGS';
ALTER TYPE "FeaturePermission" ADD VALUE IF NOT EXISTS 'EXPIRY';
ALTER TYPE "FeaturePermission" ADD VALUE IF NOT EXISTS 'LABEL_PRINT';
ALTER TYPE "FeaturePermission" ADD VALUE IF NOT EXISTS 'CAMERA_OPTIONAL';
