"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import FeedbackToast from "@/components/common/FeedbackToast";

type Channel={channel:string;displayName:string;integrationMode:string;feeRateBps:number;lastSyncMessage:string|null};
type Rate={id:string;channel:string;carrier:string;methodName:string;fee:number;maxWeightGrams:number|null;maxTotalDimensionsCm:number|null;anonymous:boolean;tracking:boolean;compensation:boolean};
export default function MarketplaceSettingsPage(){
 const [channels,setChannels]=useState<Channel[]>([]);const [rates,setRates]=useState<Rate[]>([]);const [region,setRegion]=useState({regionName:"東京都",latitude:"35.6762",longitude:"139.6503",packagingCostDefault:"100",targetProfitRateBps:"2000"});const [shipping,setShipping]=useState({channel:"all",carrier:"",methodName:"",fee:"",maxWeightGrams:"",maxTotalDimensionsCm:"",anonymous:false,tracking:true,compensation:false});const [notice,setNotice]=useState("");const [error,setError]=useState("");
 const load=async()=>{const r=await fetch("/api/admin/marketplace/listings",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.message);setChannels(d.channels);setRates(d.shippingRates);if(d.recommendationSetting)setRegion({regionName:d.recommendationSetting.regionName,latitude:String(d.recommendationSetting.latitude),longitude:String(d.recommendationSetting.longitude),packagingCostDefault:String(d.recommendationSetting.packagingCostDefault),targetProfitRateBps:String(d.recommendationSetting.targetProfitRateBps)});};useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 const post=async(body:unknown)=>{const r=await fetch("/api/admin/marketplace/advisor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.message);setNotice(d.message);await load();};
 return <main className="min-h-screen bg-slate-100 p-4 sm:p-8"><FeedbackToast tone="error" title="設定エラー" message={error} onClose={()=>setError("")}/><FeedbackToast tone="success" title="保存完了" message={notice} onClose={()=>setNotice("")}/><div className="mx-auto max-w-6xl"><header className="flex justify-between gap-3"><div><p className="text-sm font-black text-pink-700">SALES SETTINGS</p><h1 className="text-3xl font-black">販売・配送・外部連携設定</h1></div><Link href="/admin/marketplace" className="rounded-xl bg-slate-800 px-4 py-3 font-black text-white">出品管理へ</Link></header>
 <section className="mt-6 rounded-3xl bg-white p-5"><h2 className="text-xl font-black">販売地域・目標利益</h2><div className="mt-4 grid gap-3 sm:grid-cols-5">{Object.entries(region).map(([key,value])=><label key={key} className="text-xs font-bold">{{regionName:"地域名",latitude:"緯度",longitude:"経度",packagingCostDefault:"標準梱包費",targetProfitRateBps:"目標利益率(bp)"}[key]}<input value={value} onChange={e=>setRegion({...region,[key]:e.target.value})} className="mt-1 w-full rounded-lg border p-2"/></label>)}</div><button onClick={()=>void post({action:"SAVE_RECOMMENDATION_SETTING",...region,latitude:Number(region.latitude),longitude:Number(region.longitude),packagingCostDefault:Number(region.packagingCostDefault),targetProfitRateBps:Number(region.targetProfitRateBps)}).catch(e=>setError(e.message))} className="mt-4 rounded-xl bg-blue-700 px-4 py-2 font-black text-white">地域設定を保存</button></section>
 <section className="mt-6 rounded-3xl bg-white p-5"><h2 className="text-xl font-black">販売チャネル</h2><div className="mt-4 space-y-3">{channels.map(channel=><div key={channel.channel} className="grid gap-3 rounded-xl border p-4 sm:grid-cols-[1fr_180px_140px_auto]"><div><p className="font-black">{channel.displayName}</p><p className="text-xs text-slate-500">{channel.lastSyncMessage||"接続待機中"}</p></div><select defaultValue={channel.integrationMode} id={`mode-${channel.channel}`} className="rounded-lg border p-2"><option value="MANUAL">手動</option><option value="CSV">CSV</option><option value="OFFICIAL_API">公式API</option></select><input type="number" defaultValue={channel.feeRateBps} id={`fee-${channel.channel}`} className="rounded-lg border p-2"/><button onClick={()=>{const mode=(document.getElementById(`mode-${channel.channel}`) as HTMLSelectElement).value;const fee=Number((document.getElementById(`fee-${channel.channel}`) as HTMLInputElement).value);void post({action:"UPDATE_CHANNEL",channel:channel.channel,integrationMode:mode,feeRateBps:fee}).catch(e=>setError(e.message));}} className="rounded-lg bg-slate-800 px-3 py-2 font-black text-white">保存</button></div>)}</div></section>
 <section className="mt-6 rounded-3xl bg-white p-5"><h2 className="text-xl font-black">送料表</h2><p className="mt-1 text-sm text-slate-600">料金改定時は新しい料金を追加します。コード変更は不要です。</p><div className="mt-4 grid gap-2 sm:grid-cols-4"><input placeholder="配送会社" value={shipping.carrier} onChange={e=>setShipping({...shipping,carrier:e.target.value})} className="rounded-lg border p-2"/><input placeholder="発送方法" value={shipping.methodName} onChange={e=>setShipping({...shipping,methodName:e.target.value})} className="rounded-lg border p-2"/><input placeholder="送料" type="number" value={shipping.fee} onChange={e=>setShipping({...shipping,fee:e.target.value})} className="rounded-lg border p-2"/><select value={shipping.channel} onChange={e=>setShipping({...shipping,channel:e.target.value})} className="rounded-lg border p-2"><option value="all">全チャネル</option>{channels.map(c=><option key={c.channel} value={c.channel}>{c.displayName}</option>)}</select><input placeholder="最大重量g" type="number" value={shipping.maxWeightGrams} onChange={e=>setShipping({...shipping,maxWeightGrams:e.target.value})} className="rounded-lg border p-2"/><input placeholder="3辺合計cm" type="number" value={shipping.maxTotalDimensionsCm} onChange={e=>setShipping({...shipping,maxTotalDimensionsCm:e.target.value})} className="rounded-lg border p-2"/><label><input type="checkbox" checked={shipping.anonymous} onChange={e=>setShipping({...shipping,anonymous:e.target.checked})}/> 匿名</label><label><input type="checkbox" checked={shipping.compensation} onChange={e=>setShipping({...shipping,compensation:e.target.checked})}/> 補償</label></div><button onClick={()=>void post({action:"SAVE_SHIPPING_RATE",...shipping,fee:Number(shipping.fee),maxWeightGrams:Number(shipping.maxWeightGrams)||null,maxTotalDimensionsCm:Number(shipping.maxTotalDimensionsCm)||null}).catch(e=>setError(e.message))} className="mt-4 rounded-xl bg-emerald-600 px-4 py-2 font-black text-white">送料を追加</button><div className="mt-4 grid gap-2 sm:grid-cols-2">{rates.map(rate=><p key={rate.id} className="rounded-lg bg-slate-50 p-3 text-sm font-bold">{rate.carrier} {rate.methodName}：¥{rate.fee}／{rate.maxWeightGrams?`${rate.maxWeightGrams}g`:"重量制限未設定"}／{rate.maxTotalDimensionsCm?`${rate.maxTotalDimensionsCm}cm`:"サイズ未設定"}</p>)}</div></section>
 </div></main>;
}
