"use client";
import { useLiveRefresh } from "@/hooks/useLiveRefresh";
import { fetchFresh } from "@/lib/fetch-fresh";

import Link from "next/link";
import { useEffect, useState, useRef } from "react";
import FeedbackToast from "@/components/common/FeedbackToast";

type Channel={channel:string;displayName:string;integrationMode:string;feeRateBps:number;lastSyncMessage:string|null};
type Rate={id:string;channel:string;carrier:string;methodName:string;fee:number;maxWeightGrams:number|null;maxTotalDimensionsCm:number|null;anonymous:boolean;tracking:boolean;compensation:boolean};
export default function MarketplaceSettingsPage(){
 const dirty=useRef(false);
 const [channels,setChannels]=useState<Channel[]>([]);const [rates,setRates]=useState<Rate[]>([]);const [target,setTarget]=useState("20");const [shipping,setShipping]=useState({channel:"all",carrier:"",methodName:"",fee:"",maxWeightGrams:"",maxTotalDimensionsCm:"",anonymous:false,tracking:true,compensation:false});const [notice,setNotice]=useState("");const [error,setError]=useState("");
 const load=async()=>{const r=await fetchFresh("/api/admin/marketplace/listings",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.message);setChannels(d.channels);setRates(d.shippingRates);if(d.recommendationSetting)setTarget(String(d.recommendationSetting.targetProfitRateBps/100));};useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 const post=async(body:unknown)=>{const r=await fetch("/api/admin/marketplace/advisor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.message);setNotice(d.message);dirty.current=false;await load();};
 useLiveRefresh(async()=>{if(!dirty.current)await load();});
 return <main onInputCapture={()=>{dirty.current=true;}} onChangeCapture={()=>{dirty.current=true;}} className="min-h-screen bg-slate-100 p-4 sm:p-8"><FeedbackToast tone="error" title="設定エラー" message={error} onClose={()=>setError("")}/><FeedbackToast tone="success" title="保存完了" message={notice} onClose={()=>setNotice("")}/><div className="mx-auto max-w-6xl"><header className="flex justify-between gap-3"><div><p className="text-sm font-black text-pink-700">SHARED PREFERENCES</p><h1 className="text-3xl font-black">フリマの共通設定</h1></div><Link href="/marketplace" className="rounded-xl bg-slate-800 px-4 py-3 font-black text-white">出品管理へ</Link></header>
 <p className="mt-3 text-slate-600">全員で同じ設定を使います。送料の比較は出品する商品を選ぶと使えます。</p>
 <section className="mt-6 rounded-3xl bg-white p-5"><h2 className="text-xl font-black">提案する価格の目標</h2><p className="mt-2 text-sm text-slate-600">販売履歴がないとき、費用を引いた後に残したい利益の割合から目安を出します。梱包費は出品する商品ごとに入力します。</p><label className="mt-4 block text-sm font-bold">目標利益率（%）<input aria-label="目標利益率" type="number" min="0" max="90" step="0.1" value={target} onChange={e=>setTarget(e.target.value)} className="ml-3 w-24 rounded-lg border p-2"/></label><button disabled={target===""||Number(target)<0||Number(target)>90} onClick={()=>void post({action:"SAVE_RECOMMENDATION_SETTING",targetProfitRateBps:Math.round(Number(target)*100)}).catch(e=>setError(e.message))} className="mt-4 rounded-xl bg-indigo-700 px-4 py-3 font-bold text-white disabled:opacity-40">目標を保存</button></section>
 <section className="mt-6 rounded-3xl bg-white p-5"><h2 className="text-xl font-black">どこで販売するか・手数料</h2><p className="mt-2 text-sm text-slate-600">販売先ごとに利益計算へ使う割合です。出品文は販売先にコピーして登録します。ここで保存しても、外部サイトに出品されません。</p><div className="mt-4 space-y-3">{channels.map(channel=><div key={channel.channel} className="flex flex-wrap items-end gap-3 rounded-xl border p-4"><label className="min-w-0 flex-1 text-sm font-bold">{channel.displayName} の手数料（%）<input aria-label={channel.displayName+"の手数料"} type="number" min="0" max="100" step="0.1" value={channel.feeRateBps/100} onChange={e=>setChannels(rows=>rows.map(row=>row.channel===channel.channel?{...row,feeRateBps:Number(e.target.value)*100}:row))} className="mt-2 block w-full rounded-lg border p-2"/></label><button onClick={()=>void post({action:"SAVE_CHANNEL_FEE",channel:channel.channel,feeRateBps:Math.round(channel.feeRateBps)}).catch(e=>setError(e.message))} className="rounded-lg bg-slate-800 px-4 py-3 font-bold text-white">保存</button></div>)}{channels.length===0&&<p className="text-sm text-slate-600">販売先の登録がありません。メルカリ・Yahoo!フリマの提案には通常手数料の目安を使います。</p>}</div><p className="mt-3 text-xs text-slate-500">割引・キャンペーンや販売実績による料率は、販売先のアカウントで確認してください。</p></section>
 <details className="mt-6 rounded-3xl bg-white p-5"><summary className="cursor-pointer text-lg font-bold">独自の送料を登録する</summary><p className="mt-1 text-sm text-slate-600">通常は出品画面の送料候補を使ってください。ここは独自の料金表を使う場合です。登録した料金がある販売先では、その料金表を優先します。</p><div className="mt-4 grid gap-2 sm:grid-cols-4"><input placeholder="配送会社" value={shipping.carrier} onChange={e=>setShipping({...shipping,carrier:e.target.value})} className="rounded-lg border p-2"/><input placeholder="発送方法" value={shipping.methodName} onChange={e=>setShipping({...shipping,methodName:e.target.value})} className="rounded-lg border p-2"/><input placeholder="送料" type="number" value={shipping.fee} onChange={e=>setShipping({...shipping,fee:e.target.value})} className="rounded-lg border p-2"/><select value={shipping.channel} onChange={e=>setShipping({...shipping,channel:e.target.value})} className="rounded-lg border p-2"><option value="all">すべての販売先</option>{channels.map(c=><option key={c.channel} value={c.channel}>{c.displayName}</option>)}</select><input placeholder="最大重量g" type="number" value={shipping.maxWeightGrams} onChange={e=>setShipping({...shipping,maxWeightGrams:e.target.value})} className="rounded-lg border p-2"/><input placeholder="3辺合計cm" type="number" value={shipping.maxTotalDimensionsCm} onChange={e=>setShipping({...shipping,maxTotalDimensionsCm:e.target.value})} className="rounded-lg border p-2"/><label><input type="checkbox" checked={shipping.anonymous} onChange={e=>setShipping({...shipping,anonymous:e.target.checked})}/> 匿名</label><label><input type="checkbox" checked={shipping.compensation} onChange={e=>setShipping({...shipping,compensation:e.target.checked})}/> 補償</label></div><button onClick={()=>void post({action:"SAVE_SHIPPING_RATE",...shipping,fee:Number(shipping.fee),maxWeightGrams:Number(shipping.maxWeightGrams)||null,maxTotalDimensionsCm:Number(shipping.maxTotalDimensionsCm)||null}).catch(e=>setError(e.message))} className="mt-4 rounded-xl bg-emerald-600 px-4 py-2 font-black text-white">送料を追加</button><div className="mt-4 grid gap-2 sm:grid-cols-2">{rates.map(rate=><p key={rate.id} className="rounded-lg bg-slate-50 p-3 text-sm font-bold">{rate.carrier} {rate.methodName}：¥{rate.fee}／{rate.maxWeightGrams?`${rate.maxWeightGrams}g`:"重量制限未設定"}／{rate.maxTotalDimensionsCm?`${rate.maxTotalDimensionsCm}cm`:"サイズ未設定"}</p>)}</div></details>
 </div></main>;
}
