"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import FeedbackToast from "@/components/common/FeedbackToast";

type Classification = { id: string; kind: "MAJOR" | "MINOR"; name: string; parentName: string; itemCount: number; inventoryCount: number };
type Location = { id: string; name: string; description: string | null; _count: { inventories: number; itemRegistrationRequests: number } };
type Payload = { classifications: Classification[]; locations: Location[] };

export default function ClassificationsPage() {
  const [data, setData] = useState<Payload>({ classifications: [], locations: [] });
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const [majorName, setMajorName] = useState(""); const [minorName, setMinorName] = useState(""); const [minorParent, setMinorParent] = useState("");
  const [locationName, setLocationName] = useState(""); const [locationDescription, setLocationDescription] = useState("");
  const [edit, setEdit] = useState<{ type: "MAJOR" | "MINOR" | "LOCATION"; source: string; sourceId?: string; parentName?: string } | null>(null);
  const [target, setTarget] = useState(""); const [targetParent, setTargetParent] = useState("");

  const load = useCallback(async () => { const response = await fetch("/api/admin/classifications", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message ?? "分類を取得できませんでした。"); setData(payload); }, []);
  useEffect(() => { void load().catch((e) => setError(e instanceof Error ? e.message : "分類を取得できませんでした。")); }, [load]);
  const majors = useMemo(() => data.classifications.filter((row) => row.kind === "MAJOR"), [data.classifications]);
  const minors = useMemo(() => data.classifications.filter((row) => row.kind === "MINOR"), [data.classifications]);

  const execute = async (body: Record<string, unknown>) => {
    setBusy(true); setError("");
    try { const response = await fetch("/api/admin/classifications", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(`${payload.message ?? "更新できませんでした。"}${payload.code ? `（${payload.code}）` : ""}`); setNotice(payload.message); setEdit(null); setTarget(""); setTargetParent(""); await load(); }
    catch (e) { setError(e instanceof Error ? e.message : "更新できませんでした。"); } finally { setBusy(false); }
  };

  return <main className="min-h-screen bg-slate-100 p-4 text-slate-950 sm:p-8">
    <FeedbackToast tone="error" title="分類編集エラー" message={error} onClose={() => setError("")} />
    <FeedbackToast tone="success" title="更新完了" message={notice} autoCloseMs={5000} onClose={() => setNotice("")} />
    <div className="mx-auto max-w-7xl"><header className="flex flex-wrap justify-between gap-4"><div><p className="text-sm font-black tracking-widest text-indigo-700">CLASSIFICATION CONTROL</p><h1 className="mt-1 text-3xl font-black">分類・保管場所の整理</h1><p className="mt-2 text-slate-600">追加、名称変更、統合、移動、未使用分類の削除を、商品・在庫・棚卸範囲へ一括反映します。</p></div><Link href="/admin" className="h-fit rounded-xl bg-slate-800 px-4 py-3 font-black text-white">システム管理へ</Link></header>
      <section className="mt-6 grid gap-5 lg:grid-cols-3">
        <div className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">大分類</h2><div className="mt-4 flex gap-2"><input value={majorName} onChange={(e)=>setMajorName(e.target.value)} placeholder="追加する大分類" className="min-w-0 flex-1 rounded-xl border p-3"/><button disabled={busy||!majorName.trim()} onClick={()=>void execute({action:"CREATE_CLASSIFICATION",kind:"MAJOR",name:majorName}).then(()=>setMajorName(""))} className="rounded-xl bg-indigo-600 px-4 font-black text-white disabled:opacity-40">追加</button></div><div className="mt-4 space-y-2">{majors.map(row=><div key={row.id} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><div><p className="font-black">{row.name}</p><p className="text-xs text-slate-500">商品{row.itemCount}件・在庫{row.inventoryCount}件</p></div><button onClick={()=>{setEdit({type:"MAJOR",source:row.name});setTarget("");}} className="rounded-lg bg-slate-100 px-3 font-bold">編集</button></div></div>)}</div></div>
        <div className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">小分類</h2><div className="mt-4 grid gap-2"><select value={minorParent} onChange={(e)=>setMinorParent(e.target.value)} className="rounded-xl border p-3"><option value="">親の大分類</option>{majors.map(row=><option key={row.id}>{row.name}</option>)}</select><div className="flex gap-2"><input value={minorName} onChange={(e)=>setMinorName(e.target.value)} placeholder="追加する小分類" className="min-w-0 flex-1 rounded-xl border p-3"/><button disabled={busy||!minorName.trim()||!minorParent} onClick={()=>void execute({action:"CREATE_CLASSIFICATION",kind:"MINOR",name:minorName,parentName:minorParent}).then(()=>setMinorName(""))} className="rounded-xl bg-cyan-600 px-4 font-black text-white disabled:opacity-40">追加</button></div></div><div className="mt-4 max-h-[500px] space-y-2 overflow-auto">{minors.map(row=><div key={row.id} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><div><p className="font-black">{row.name}</p><p className="text-xs text-slate-500">{row.parentName}／商品{row.itemCount}件</p></div><button onClick={()=>{setEdit({type:"MINOR",source:row.name,parentName:row.parentName});setTarget("");setTargetParent(row.parentName);}} className="rounded-lg bg-slate-100 px-3 font-bold">編集</button></div></div>)}</div></div>
        <div className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">保管場所</h2><div className="mt-4 grid gap-2"><input value={locationName} onChange={(e)=>setLocationName(e.target.value)} placeholder="追加する保管場所" className="rounded-xl border p-3"/><input value={locationDescription} onChange={(e)=>setLocationDescription(e.target.value)} placeholder="説明" className="rounded-xl border p-3"/><button disabled={busy||!locationName.trim()} onClick={()=>void execute({action:"CREATE_LOCATION",name:locationName,description:locationDescription}).then(()=>{setLocationName("");setLocationDescription("");})} className="rounded-xl bg-emerald-600 p-3 font-black text-white disabled:opacity-40">保管場所を追加</button></div><div className="mt-4 space-y-2">{data.locations.map(row=><div key={row.id} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><div><p className="font-black">{row.name}</p><p className="text-xs text-slate-500">在庫明細{row._count.inventories}件</p></div><button onClick={()=>{setEdit({type:"LOCATION",source:row.name,sourceId:row.id});setTarget("");}} className="rounded-lg bg-slate-100 px-3 font-bold">編集</button></div></div>)}</div></div>
      </section>
    </div>
    {edit&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><section className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><p className="text-sm font-black text-indigo-700">変更元</p><h2 className="mt-1 text-2xl font-black">{edit.source}</h2><p className="mt-2 text-sm text-slate-600">名称変更は新しい名前を入力します。既存名を指定すると統合になります。在庫・棚卸範囲・履歴の参照も更新されます。</p>{edit.type==="LOCATION"?<select value={target} onChange={(e)=>setTarget(e.target.value)} className="mt-5 w-full rounded-xl border p-3"><option value="">統合先を選択（新名称なら下へ入力）</option>{data.locations.filter(row=>row.id!==edit.sourceId).map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select>:<input value={target} onChange={(e)=>setTarget(e.target.value)} placeholder="変更・統合先の分類名" className="mt-5 w-full rounded-xl border p-3"/>}{edit.type==="MINOR"&&<select value={targetParent} onChange={(e)=>setTargetParent(e.target.value)} className="mt-3 w-full rounded-xl border p-3">{majors.map(row=><option key={row.id}>{row.name}</option>)}</select>}{edit.type==="LOCATION"&&<input value={target.startsWith("new:")?target.slice(4):""} onChange={(e)=>setTarget(`new:${e.target.value}`)} placeholder="または新しい保管場所名" className="mt-3 w-full rounded-xl border p-3"/>}<div className="mt-5 grid gap-2 sm:grid-cols-3"><button disabled={busy||!target} onClick={()=>{if(edit.type==="LOCATION"){if(target.startsWith("new:"))void execute({action:"RENAME_LOCATION",sourceId:edit.sourceId,target:target.slice(4)});else void execute({action:"MERGE_LOCATION",sourceId:edit.sourceId,targetId:target});}else void execute({action:"RENAME_OR_MERGE_CLASSIFICATION",kind:edit.type,source:edit.source,target,parentName:edit.parentName,targetParent});}} className="rounded-xl bg-indigo-600 p-3 font-black text-white disabled:opacity-40">変更・統合</button>{edit.type!=="LOCATION"&&<button disabled={busy} onClick={()=>void execute({action:"DELETE_CLASSIFICATION",kind:edit.type,source:edit.source,parentName:edit.parentName})} className="rounded-xl bg-red-600 p-3 font-black text-white">未使用なら削除</button>}<button onClick={()=>setEdit(null)} className="rounded-xl bg-slate-200 p-3 font-black">戻る</button></div></section></div>}
  </main>;
}
