"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import FeedbackToast from "@/components/common/FeedbackToast";

type Recommendation = {
  inventoryInstanceId: string; itemName: string; totalQuantity: number;
  fleaMarketReserved: number; storageAvailable: number; score: number;
  reasons: string[]; acquisitionCost: number | null; packageWeightGrams: number | null;
  packageLengthCm: number | null; packageWidthCm: number | null; packageHeightCm: number | null;
};
type Advisor = { setting: { regionName: string }; weather: { summary: string }; seasonalWords: string[]; medianSoldPrice: number | null; soldSampleCount: number; recommendations: Recommendation[] };
type Method = { id:string; carrier:string; methodName:string; fee:number; anonymous:boolean; tracking:boolean; compensation:boolean; profit:number; profitRateBps:number; recommendedMinimumPrice:number };

export default function MarketplaceAdvisorPage() {
  const [advisor,setAdvisor]=useState<Advisor|null>(null);
  const [selected,setSelected]=useState<Recommendation|null>(null);
  const [price,setPrice]=useState(""); const [channel,setChannel]=useState("mercari");
  const [methods,setMethods]=useState<Method[]>([]); const [dimensionsComplete,setDimensionsComplete]=useState(true);
  const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [working,setWorking]=useState(false);
  const load=async()=>{ const r=await fetch("/api/admin/marketplace/advisor",{cache:"no-store"}); const d=await r.json(); if(!r.ok)throw new Error(d.message); setAdvisor(d); setSelected((current)=>current??d.recommendations[0]??null); };
  useEffect(()=>{void load().catch((e)=>setError(e instanceof Error?e.message:"取得できませんでした。"));},[]);
  const updateSpec=(key:keyof Recommendation,value:string)=>selected&&setSelected({...selected,[key]:value===""?null:Number(value)});
  const saveSpecs=async()=>{if(!selected)return;setWorking(true);try{const r=await fetch("/api/admin/marketplace/advisor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"SAVE_INVENTORY_SPECS",...selected})});const d=await r.json();if(!r.ok)throw new Error(d.message);setNotice(d.message);await load();}catch(e){setError(e instanceof Error?e.message:"保存できませんでした。");}finally{setWorking(false);}};
  const calculate=async()=>{if(!selected)return;setWorking(true);try{const r=await fetch("/api/admin/marketplace/profit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({inventoryInstanceId:selected.inventoryInstanceId,channel,price:Number(price)})});const d=await r.json();if(!r.ok)throw new Error(d.message);setMethods(d.methods);setDimensionsComplete(d.dimensionsComplete);const warnings=[!d.feeConfigured&&"販売手数料が未設定です。設定画面で最新の料率を登録してください。",!d.shippingConfigured&&"送料表が未設定です。発送方法と料金を登録してください。",d.shippingConfigured&&!d.shippingMatched&&"寸法・重量に合う発送方法がありません。梱包情報か送料表を確認してください。"].filter(Boolean) as string[];setError(warnings.join("\n"));}catch(e){setError(e instanceof Error?e.message:"計算できませんでした。");}finally{setWorking(false);}};
  return <main className="min-h-screen bg-slate-100 p-4 text-slate-950 sm:p-8">
    <FeedbackToast tone="error" title="販売提案エラー" message={error} onClose={()=>setError("")}/><FeedbackToast tone="success" title="保存完了" message={notice} onClose={()=>setNotice("")}/>
    <div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-black text-violet-700">SALES ADVISOR</p><h1 className="mt-1 text-3xl font-black">価格・送料・季節販売アドバイザー</h1></div><Link href="/admin/marketplace" className="rounded-xl bg-slate-800 px-5 py-3 font-black text-white">出品管理へ</Link></header>
    {advisor&&<><section className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-blue-700 p-5 text-white"><p className="text-sm font-bold">{advisor.setting.regionName}の天候</p><p className="mt-2 text-lg font-black">{advisor.weather.summary}</p></div><div className="rounded-2xl bg-amber-400 p-5"><p className="text-sm font-bold">季節キーワード</p><p className="mt-2 font-black">{advisor.seasonalWords.join("・")}</p></div><div className="rounded-2xl bg-emerald-600 p-5 text-white"><p className="text-sm font-bold">販売実績</p><p className="mt-2 text-xl font-black">中央値 {advisor.medianSoldPrice?`¥${advisor.medianSoldPrice.toLocaleString("ja-JP")}`:"実績不足"}</p><p className="text-xs">{advisor.soldSampleCount}件</p></div></section>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_1.2fr]"><section className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">出品候補</h2><div className="mt-4 max-h-[680px] space-y-2 overflow-auto">{advisor.recommendations.map((item)=><button key={item.inventoryInstanceId} onClick={()=>{setSelected(item);setMethods([]);}} className={`w-full rounded-xl border-2 p-4 text-left ${selected?.inventoryInstanceId===item.inventoryInstanceId?"border-violet-600 bg-violet-50":"border-slate-100"}`}><div className="flex justify-between gap-2"><span className="font-black">{item.itemName}</span><span className="rounded-full bg-slate-900 px-2 py-1 text-xs font-black text-white">提案度 {item.score}</span></div><p className="mt-2 text-sm">保管可能 {item.storageAvailable}／フリマ引当 {item.fleaMarketReserved}／総数 {item.totalQuantity}</p><p className="mt-1 text-xs font-bold text-violet-700">{item.reasons.join("・")||"在庫数・保管期間から候補化"}</p></button>)}</div></section>
    {selected&&<section className="space-y-5"><div className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">原価・梱包情報</h2><p className="mt-1 font-bold text-slate-600">{selected.itemName}</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-5">{[["acquisitionCost","原価"],["packageWeightGrams","重量g"],["packageLengthCm","長さcm"],["packageWidthCm","幅cm"],["packageHeightCm","高さcm"]].map(([key,label])=><label key={key} className="text-xs font-bold">{label}<input type="number" value={String(selected[key as keyof Recommendation]??"")} onChange={(e)=>updateSpec(key as keyof Recommendation,e.target.value)} className="mt-1 w-full rounded-lg border p-2"/></label>)}</div><button disabled={working} onClick={()=>void saveSpecs()} className="mt-4 rounded-xl bg-slate-800 px-4 py-2 font-black text-white">保存</button></div>
    <div className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">利益・発送方法比較</h2><div className="mt-4 grid grid-cols-2 gap-3"><select value={channel} onChange={(e)=>setChannel(e.target.value)} className="rounded-xl border p-3"><option value="mercari">メルカリ</option><option value="rakuma">ラクマ</option><option value="yahoo_furima">Yahoo!フリマ</option><option value="flea_market">フリマ共通</option></select><input type="number" value={price} onChange={(e)=>setPrice(e.target.value)} placeholder="販売価格" className="rounded-xl border p-3"/></div><button disabled={working||!price} onClick={()=>void calculate()} className="mt-4 rounded-xl bg-violet-700 px-5 py-3 font-black text-white">送料と利益を計算</button>{methods.length>0&&<div className="mt-5 space-y-3">{!dimensionsComplete&&<p className="rounded-xl bg-amber-100 p-3 text-sm font-bold text-amber-900">寸法・重量が未入力のため発送方法を正確に絞れません。</p>}{methods.map((method)=><div key={method.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><p className="font-black">{method.carrier} {method.methodName}</p><p className={method.profit>=0?"text-xl font-black text-emerald-700":"text-xl font-black text-red-700"}>利益 ¥{method.profit.toLocaleString("ja-JP")}</p></div><p className="mt-2 text-sm">送料 ¥{method.fee}／利益率 {(method.profitRateBps/100).toFixed(1)}%／推奨最低価格 ¥{method.recommendedMinimumPrice.toLocaleString("ja-JP")}</p><p className="mt-1 text-xs font-bold text-blue-700">{[method.anonymous&&"匿名",method.tracking&&"追跡",method.compensation&&"補償"].filter(Boolean).join("・")||"条件確認"}</p></div>)}</div>}</div></section>}</div></>}
    </div></main>;
}
